// Marlin/Configuration.h
#pragma once

#define STRING_CONFIG_H_AUTHOR "(Code Copilot, Ender3V1 4.2.2)"
#define CUSTOM_MACHINE_NAME    "Ender-3 V1 (4.2.2)"

// Serial
#define SERIAL_PORT 1
#define BAUDRATE 115200

// Board
#define MOTHERBOARD BOARD_CREALITY_V4
#define RET6_12864_LCD
#define POWER_SUPPLY 0

// Thermal
#define TEMP_SENSOR_0 1
#define TEMP_SENSOR_BED 1
#define HEATER_0_MINTEMP 5
#define HEATER_0_MAXTEMP 275
#define BED_MINTEMP 5
#define BED_MAXTEMP 120

#define PIDTEMP
#define DEFAULT_Kp 22.20
#define DEFAULT_Ki 1.08
#define DEFAULT_Kd 114.00
// #define PIDTEMPBED

// Volume
#define X_BED_SIZE 220
#define Y_BED_SIZE 220
#define Z_MAX_POS 250

// Motion
#define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, 400, 93 }
#define DEFAULT_MAX_FEEDRATE          { 500, 500, 5, 25 }
#define DEFAULT_MAX_ACCELERATION      { 500, 500, 100, 500 }

#define CLASSIC_JERK
#define DEFAULT_XJERK 8.0
#define DEFAULT_YJERK 8.0
#define DEFAULT_ZJERK 0.4
#define DEFAULT_EJERK 5.0
#define S_CURVE_ACCELERATION

// Drivers
#define X_DRIVER_TYPE A4988
#define Y_DRIVER_TYPE A4988
#define Z_DRIVER_TYPE A4988
#define E0_DRIVER_TYPE A4988

// Endstops
#define USE_XMIN_PLUG
#define USE_YMIN_PLUG
#define USE_ZMIN_PLUG
#define X_MIN_ENDSTOP_INVERTING true
#define Y_MIN_ENDSTOP_INVERTING true
#define Z_MIN_ENDSTOP_INVERTING true

// Leveling (Manual Mesh 4×4 + edit single points)
#define MESH_BED_LEVELING
#define LCD_BED_LEVELING
#define MESH_EDIT_MENU
#define GRID_MAX_POINTS_X 4
#define GRID_MAX_POINTS_Y 4
#define RESTORE_LEVELING_AFTER_G28
#define ENABLE_LEVELING_FADE_HEIGHT

// Tramming Wizard
#define LEVEL_BED_CORNERS
#define LEVEL_CORNERS_INSET 30
#define LEVEL_CORNERS_Z_HOP  4

// EEPROM
#define EEPROM_SETTINGS
#define EEPROM_AUTO_INIT

// UI / SD
#define CR10_STOCKDISPLAY
#define LCD_LANGUAGE en
#define INDIVIDUAL_AXIS_HOMING_MENU
#define NOZZLE_PARK_FEATURE
#define ADVANCED_PAUSE_FEATURE
#define SDSUPPORT

// Preheat
#define PREHEAT_1_LABEL       "PLA"
#define PREHEAT_1_TEMP_HOTEND 200
#define PREHEAT_1_TEMP_BED    60
#define PREHEAT_1_FAN_SPEED   0
#define PREHEAT_2_LABEL       "PETG"
#define PREHEAT_2_TEMP_HOTEND 240
#define PREHEAT_2_TEMP_BED    80
#define PREHEAT_2_FAN_SPEED   0

// Safety
#define THERMAL_PROTECTION_HOTENDS
#define THERMAL_PROTECTION_BED
#define WATCH_TEMP_PERIOD 40
#define WATCH_TEMP_INCREASE 2
