// Marlin/Configuration_adv.h
#pragma once

// UI comfort
#define BABYSTEPPING
#define BABYSTEP_ZPROBE_OFFSET
#define DOUBLECLICK_FOR_Z_BABYSTEPPING
#define PID_EDIT_MENU
#define PID_AUTOTUNE_MENU

// Custom screens
#define CUSTOM_BOOTSCREEN
#define SHOW_CUSTOM_BOOTSCREEN
#define BOOTSCREEN_TIMEOUT 3000
#define CUSTOM_STATUS_SCREEN_IMAGE

// SD / Files
#define SD_CHECK_AND_RETRY
#define LONG_FILENAME_HOST_SUPPORT
#define SDCARD_SORT_ALPHA
#define SDSORT_LIMIT 20

// Misc
#define NOZZLE_PARK_FEATURE
#define ADVANCED_PAUSE_FEATURE
