# .github/workflows/build-marlin.yml
name: Build Marlin (Ender3V1 4.2.2 - 4x4 MBL)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PIO_ENV: STM32F103RE_creality   # ✅ correct env for Creality 4.2.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install PlatformIO
        run: pip install -U platformio

      - name: Build (${{ env.PIO_ENV }})
        run: pio run -e ${{ env.PIO_ENV }}

      - name: List build outputs
        run: ls -la .pio/build/${{ env.PIO_ENV }} || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ender3V1_422_4x4MBL_${{ env.PIO_ENV }}
          path: .pio/build/${{ env.PIO_ENV }}/firmware.bin
          if-no-files-found: error
